spring.application.name=catalog

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/payments
spring.datasource.username=admin
spring.datasource.password=password

jwt.secret=Q0hBVkVfU0VDUkVUQV9NVUlUT19MT05HQV9FX0NPTVBMRVhBX1BBUkFfQVNTSU5BVFVSQQ==
jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG